package eu.kanade.tachiyomi.extension.en.isekaiscancom

import eu.kanade.tachiyomi.multisrc.madara.Madara

class IsekaiScanCom : Madara("IsekaiScan.com", "https://isekaiscan.com", "en") {
    override fun getGenreList() = listOf(
        Genre("4 koma", "4-koma"),
        Genre("Action", "action"),
        Genre("Adventure", "adventure"),
        Genre("Comedy", "comedy"),
        Genre("Cooking", "cooking"),
        Genre("Crime", "crime"),
        Genre("Crossdressing", "crossdressing"),
        Genre("Doujinshi", "doujinshi"),
        Genre("Drama", "drama"),
        Genre("Ecchi", "ecchi"),
        Genre("Ecchi 2", "ecchi-2"),
        Genre("Fantasy", "fantasy"),
        Genre("Gender bender", "gender-bender"),
        Genre("Genderswap", "genderswap"),
        Genre("Ghost", "ghost"),
        Genre("Gore", "gore"),
        Genre("Gyaru", "gyaru"),
        Genre("Harem", "harem"),
        Genre("Historical", "historical"),
        Genre("Horror", "horror"),
        Genre("Indonesian", "indonesian"),
        Genre("Isekai", "isekai"),
        Genre("Josei", "josei"),
        Genre("Loli", "loli"),
        Genre("Mafia", "mafia"),
        Genre("Magic", "magic"),
        Genre("Manhua", "manhua"),
        Genre("Manhwa", "manhwa"),
        Genre("Martial arts", "martial-arts"),
        Genre("Mature", "mature"),
        Genre("Mature 2", "adult"), //site says Mature 2 but the value is adult
        Genre("Mature 3", "mature-3"),
        Genre("Mecha", "mecha"),
        Genre("Medical", "medical"),
        Genre("Military", "military"),
        Genre("Monster", "monster"),
        Genre("Monster girls", "monster-girls"),
        Genre("Music", "music"),
        Genre("Mystery", "mystery"),
        Genre("Polish Comics", "polish-comics"),
        Genre("Post apocalyptic", "post-apocalyptic"),
        Genre("Psychological", "psychological"),
        Genre("Reincarnation", "reincarnation"),
        Genre("Reverse harem", "reverse-harem"),
        Genre("Romance", "romance"),
        Genre("Seinen", "seinen"),
        Genre("Shota", "shota"),
        Genre("Shoujo", "shoujo"),
        Genre("Shoujo ai", "shoujo-ai"),
        Genre("Shounen", "shounen"),
        Genre("Shounen ai", "shounen-ai"),
        Genre("Si-fi", "si-fi"),
        Genre("Slice of Life", "slice-of-life"),
        Genre("Sports", "sports"),
        Genre("Superhero", "superhero"),
        Genre("Supernatural", "supernatural"),
        Genre("Time travel", "time-travel"),
        Genre("Tragedy", "tragedy"),
        Genre("Villainess", "villainess"),
        Genre("Yaoi", "yaoi"),
        Genre("Yuri", "yuri"),
        Genre("Zombies", "zombies"),
    )
}
