package eu.kanade.tachiyomi.animeextension.en.marinmoe

object MarinMoeConstants {
    val groupEntries = arrayOf(
        "Site Default", "-__-`", "-.-", "Abstinence", "AC_", "ADZ Subs", "Afternoon Naps Empire", "Almighty", "Alt",
        "Anime Noobs Fansubbers", "Anime-4ever", "Anime-Conan", "Anime-Destiny", "Anime-Empire", "Anime-FanRips",
        "Anime-Fury", "Anime-Jiyuu", "Anime-Supreme", "anime4life.", "AnimeBytes Remuxes", "AnimeOne", "AnimeSenshi Subs",
        "AnimeYuki", "Anonymous", "Anonymous Russian Rippers", "AOmundson", "ARC", "Aria", "Arid", "aRMX", "aro",
        "Asakura", "asc3nsi0n", "Asteroid", "AtlasSubbed", "Ayashii", "AZ Fansubs", "AZ Fansubs & Baka-Gaijin", "B2E",
        "Baaro", "Baka-Gaijin & Detective Conan Files", "BakaBT Remuxes", "Bakahorizonsama", "BananaBoat", "Beatrice-Raws",
        "Black Organization", "BluDragon", "BlurayDesuYo", "bradosia", "Bunny Hat Raw", "C137", "Cait-Sidhe",
        "Cartoon-World", "Catar", "CBT", "Chihiro-Fansubs", "Chosensilver Remux", "Chotab", "CitadelofTheRaven", "Clara",
        "Cman21", "Coalgirls", "Cold Fusion", "Cold Fusion & Baaro", "coldhell", "ColorMeSubbed", "Commie", "Commsei",
        "cornbreadman", "Crow", "Cry", "CsS", "CUNNY", "D.O.M.O.", "DameDesuYo", "DarkDream", "darkfire68",
        "Darkonius & wisperer", "Datte13", "deanzel", "Detective Conan Translation Project",
        "Detective Conan Translation Project & AZ Fansubs", "Detective Conan Translation Project & Kienai-Niji",
        "Detective Conan Translation Project & NazoNoKami", "Detective Conan Translation Project & The Moonlighters",
        "Deus EX Anima", "DigitalPanic", "DigitalSubs", "Dknight", "DmonHiro", "Doki Fansubs",
        "Doki Fansubs & Chihiro Fansubs", "DorianHD", "DorianHD & FoxesDen", "Doutei Fansubs", "Drag", "drawn-reality",
        "Dual Audio Empire", "EightBit", "Elysium Subs", "EMBER", "Enceladus", "EncoderAnon", "Encodergasm", "entameSubs",
        "Erai-raws", "Exiled-Destiny", "ExoDus", "Explorer", "eXterminator", "Fansubber-ES", "FFFpeeps",
        "FFFpeeps & Interrobang", "FFFpeeps & Kantai-Subs", "FFFpeeps & Vivid Subs", "Final8", "Flamwenco", "FLUX",
        "Frostii & AnimeONE", "Funnuraba Fansubs", "Galator", "Gekkostate", "GHOST", "ghostosenpai", "Glenn", "Glue",
        "Godim", "Godless-Orphan", "Golosubs", "Golumpa", "good", "Good Job! Media", "Good Job! Media & Kaleido-subs",
        "GotWoot Fansubs", "Grim Ripper", "Grim-F", "gskumar", "GST", "GUDish", "HachiRokuNiSanKyu", "Hari-No-Ito",
        "Hark0n", "Harunatsu Fansubs", "hchcsen", "High Quality Releases", "Holomux", "HorribleSubs", "hose", "Hotaru",
        "iAHD", "If you don`t download this I will cry", "IK-User", "iKaos", "Inka-Subs", "InoBestGirl", "Inverti", "ITH",
        "Iznjie Biznjie", "jackie", "joseole99", "JPSDR", "Judgment", "Jumonji-Giri", "JustAnotherRemux", "JySzE",
        "KaizouFansubs", "Kaleido-subs", "Kaleido-subs & Flax Subs", "Kaleido-subs & Scyrous", "Kametsu", "Kantai-Subs",
        "karios", "Karma Rips", "Kawaii", "Kawaiika-Raws", "Kaze no Koe Fansubs", "kBaraka", "KH", "Kienai",
        "Kienai-Niji & AZ FAnsubs", "Kira_SEV", "Kira-Fansub", "Kiriya", "KiteSeekers & Kira-Fansub",
        "KiteSeekers & Licca Fansubs", "KOSMOS", "Koten Gars", "KOTEX", "kuchikirukia", "Kulot", "Kyozoku", "Laidback",
        "Last Resort Encodes", "Late Night Snack", "Lazy Lily Subs", "Legion", "Lisata598", "Live-eviL", "LostYears",
        "Lulu", "MaskedCape", "Mazui", "MeruMeruSubs", "MetalicBox", "Metaljerk", "Mew", "Migoto Fansubs", "Moodkiller",
        "Moodkiller & Scyrous", "Moozzi2", "motbob", "mottoj-anime", "MoyaiSubs", "Mysteria", "NanDesuKa?", "NazoNoKami",
        "NazoNoKami & KaizouFansubs", "NC-Raws", "neko-raws", "NekomimiTeikoku", "neo1024", "Nep Blanc", "Netaro",
        "NetflixSucks", "NeutralHatred", "nielsen145", "nImEHuntetD", "Nineball", "Nofunloli", "Noms", "NovaWorks",
        "Nuke Fansubs", "Nyanpasu Subs", "Okay-Subs", "Orphan", "Orphan & macros74", "owowo", "oZanderr", "OZC Anime",
        "Patjantess", "Pineapple Salad", "PiPoPaHd", "pls", "Pog42", "Polished Subs", "pooookie", "Puto", "pyroneko",
        "Quetzal", "Quickie", "Raizel", "Rakuda", "RASETSU", "Real-Anime Xtreme", "ReDone-Subs", "ReinForce",
        "Reito`s Rockin Rips", "RemuxBobP", "Retrofit", "rickyhorror", "Rising Sun", "RMX", "Robonation", "Rom & Rem",
        "Saizen Fansubs", "Saizen-Fansubs & Ignition-One", "SakuraCircle", "SallySubs", "samaritan", "SchwingBoner",
        "Scriptum", "Scyrous", "Sea of Serenity Subs", "Serenae", "ShadyCrab", "Shimatta", "Shindou-Anime",
        "Shining Fansubs", "ShiraRaminz", "Shirase", "Shirσ", "Shisukon", "Smoke", "smoon", "SmugCat", "SmugMug", "SNSbu",
        "Solar Fansubs", "solaufein", "SSP-Corp", "Static-Subs & AnimeYuki", "Static-Subs & Eclipse Productions",
        "SubsPlease", "Suiri Otaku", "Sushi Fansubs", "sxales", "Tamaya", "Tap24", "The Moonlighters", "The0x539",
        "Thighs", "Tipota Encodes", "tlacatlc6", "ToTheGlory Anime", "Tsundere Rips", "TV-Nihon", "Underwater",
        "Unlimited Translation Works", "Unlimited Translation Works & Mazui", "unwanteddubfan", "Ureshii", "Vanilla",
        "Virus123", "Vivid Subs", "Vodes", "Waku", "Wasurenai Fansubs", "Wasurenai Fansubs & Anime-Himitsu", "WAVE",
        "WhoBeDaPlaya", "WhyNot?", "WIP", "Wyse", "Xanth", "xCryptic", "xKrptonicz", "Xonline", "xPearse", "xxon", "YA",
        "Yameii", "Yami-Fansubs", "YamiWheeler", "Yellow-Flash", "Yousoro", "YURI", "Z4ST1N", "zangafan", "ZetaRebel",
        "Zurako Subs",
    )

    val groupEntryValues = arrayOf(
        "site_default", "-__-`", "-.-", "Abstinence", "AC", "ADZ", "ANE", "Almighty", "Alt", "anfs", "a4e", "AConan", "A-Destiny", "A-E",
        "A-FanRips", "A-Fury", "Ani-Jiyuu", "a-S", "anime4life.", "AB-RMX", "AonE", "Asenshi", "AnY", "None", "ARR",
        "AOmundson", "ARC", "Aria", "Arid", "None", "aro", "Asakura", "ASC", "Asteroid", "AtlasSubbed", "Ayashii", "AZFS",
        "AZFS-BG", "B2E", "Baaro", "BG-DCF", "BBT-RMX", "BHS", "BananaBoat", "Beatrice-Raws", "B-Org", "BluDragon", "None",
        "ASO", "Bunny Hat Raw", "C137", "Cait-Sidhe", "C-W", "CTR", "CBT", "Chihiro", "CsRmX", "Chotab", "COR", "Clara",
        "Cman", "Coalgirls", "ColdFusion", "CF&B", "None", "CMS", "Commie", "Commsei", "CBM", "Crow", "Cry", "None",
        "CUNNY", "DOMO", "DameDesuYo", "DarkDream", "df68", "DarkWispers", "Datte13", "deanzel", "DCTP", "DCTP-AZFS",
        "DCTP-Kienai", "DCTP-Neg", "DCTP-M-L", "DEXA", "dp", "Digital", "DKnt", "None", "Doki", "Doki-Chihiro", "DHD",
        "DHD-FD", "Doutei", "Drag", "None", "DAE", "EightBit", "Elysium", "EMBER", "Enceladus", "EncAnon", "EG",
        "entameSubs", "Erai-raws", "E-D", "eXo", "Exp", "eXterminator", "EUR", "FFF", "FBI", "FFF-Kantai", "FFF-Vivid",
        "Final8", "Flamwenco", "FLUX", "Frostii_AonE", "Funnuraba", "Galator", "GS", "GHOST", "GHS", "Glenn", "Glue",
        "Godim", "None", "Golo", "Golumpa", "None", "GJM", "GJM-Kaleido", "GotWoot", "GrimRipper", "grimf", "GSK_kun",
        "GST", "GUDish", "HachiRoku", "HnI", "Hark0n", "Harunatsu", "hchcsen", "HQR", "Holomux", "None", "hose", "None",
        "iAHD", "DownloadThisOrIWillCry", "IK", "iKaos", "Inka-Subs", "InoBestGirl", "Inverti", "ITH", "Iznjie Biznjie",
        "jackie", "joseole99", "JPSDR", "Judgment", "J-G", "JAR", "JySzE", "Kaizou", "Kaleido-subs", "Kaleido-Flax",
        "Kaleido-SCY", "Kametsu", "Kantai", "karios", "None", "None", "Kawaiika-Raws", "KnKF", "kBaraka", "KH", "Kienai",
        "Kienai-AZFS", "SEV", "Kira-Fansub", "Kiriya", "KiteSeekers-Kira", "KiteSeekers-Licca", "KOSMOS", "Koten_Gars",
        "None", "kuchikirukia", "Kulot", "Kyo", "None", "LRE", "None", "Lazy Lily", "Legion", "Lisata598", "L-E",
        "LostYears", "None", "MC", "Mazui", "MeruMeruSubs", "Metal", "Metaljerk", "Mew", "Migoto", "MK", "MK-SCY",
        "Moozzi2", "MTBB", "None", "MoyaiSubs", "Mysteria", "NanDesuKa", "Neg", "Neg & Kaizou", "NC-Raws", "neko-raws",
        "NMTK", "neo1024", "Nep_Blanc", "Netaro", "NetflixSucks", "NH", "nielsen145", "nImEHuntetD", "9ball", "Nofunloli",
        "Noms", "NovaWorks", "Nuke", "Nyanpasu", "Okay-Subs", "Orphan", "Orphan-M74", "OWO", "OZR", "OZC", "Patjantess",
        "Pineapple Salad", "PiPoPaHd", "pls", "Pog42", "polished", "Pookie", "Puto", "None", "Quetzal", "Quickie",
        "Raizel", "Rakuda", "RASETSU", "RaX", "ReDone", "ReinForce", "3xR", "BobP", "Retrofit", "RH", "Rising Sun", "None",
        "Rn", "Rom & Rem", "Saizen", "SZN & I-O", "None", "None", "sam", "SchwingBoner", "Scriptum", "SCY", "SOSSubs",
        "Serenae", "ShadyCrab", "Shimatta", "S-A", "Shi-Fa", "ShiraRaminz", "Shirase", "Shirσ", "Shisukon", "None",
        "smoon", "SmugCat", "SmugMug", "None", "Solar", "SOLA", "SSP-Corp", "SS-AnY", "SS-Eclipse", "SubsPlease",
        "SuiriOtaku", "Sushi", "sxales", "Tamaya", "Tap24", "M-L", "The0x539", "Thighs", "tipota", "None", "TTGA",
        "Tsundere", "T-N", "Underwater", "UTW", "UTW-Mazui", "UDF", "Ureshii", "Vanilla", "Virus123", "Vivid", "Vodes",
        "Waku", "Wasurenai", "Wasurenai-Himitsu", "WAVE", "WBDP", "WhyNot", "WIP", "WSE", "Xanth", "CyC", "KRP", "Xonline",
        "xPearse", "xxon", "YA", "Yameii", "Yami", "None", "Yellow-Flash", "Yousoro", "YURI", "Z4ST1N", "zang",
        "ZetaRebel", "Zurako",
    )
}
