package eu.kanade.tachiyomi.animeextension.en.marinmoe

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList

object MarinMoeFilters {
    open class QueryPartFilter(
        displayName: String,
        val vals: Array<Pair<String, String>>,
    ) : AnimeFilter.Select<String>(
        displayName,
        vals.map { it.first }.toTypedArray(),
    ) {
        fun toQueryPart() = vals[state].second
    }

    open class CheckBoxFilterList(name: String, values: List<CheckBox>) : AnimeFilter.Group<AnimeFilter.CheckBox>(name, values)
    private class CheckBoxVal(name: String, state: Boolean = false) : AnimeFilter.CheckBox(name, state)

    private inline fun <reified R> AnimeFilterList.asQueryPart(): String {
        return this.filterIsInstance<R>().joinToString("") {
            (it as QueryPartFilter).toQueryPart()
        }
    }

    class SortFilter : QueryPartFilter("Sort order", MarinMoeFiltersData.sort)

    class TypeFilter : CheckBoxFilterList(
        "Type",
        MarinMoeFiltersData.types.map { CheckBoxVal(it.first, true) },
    )

    class StatusFilter : CheckBoxFilterList(
        "Status",
        MarinMoeFiltersData.status.map { CheckBoxVal(it.first, true) },
    )

    class ContentRatingFilter : CheckBoxFilterList(
        "Content Rating",
        MarinMoeFiltersData.contentRating.map { CheckBoxVal(it.first, true) },
    )

    class SourceFilter : CheckBoxFilterList(
        "Source",
        MarinMoeFiltersData.source.map { CheckBoxVal(it.first, false) },
    )

    class GenreFilter : CheckBoxFilterList(
        "Genre",
        MarinMoeFiltersData.genre.map { CheckBoxVal(it.first, false) },
    )

    class GroupFilter : QueryPartFilter("Group", MarinMoeFiltersData.groups)

    class StudioFilter : QueryPartFilter("Studio", MarinMoeFiltersData.studios)

    val filterList = AnimeFilterList(
        SortFilter(),
        AnimeFilter.Separator(),
        TypeFilter(),
        StatusFilter(),
        ContentRatingFilter(),
        SourceFilter(),
        AnimeFilter.Separator(),
        GenreFilter(),
        GroupFilter(),
        StudioFilter(),
    )

    data class FilterSearchParams(
        val sort: String = "",
        val type: String = "",
        val status: String = "",
        val contentRating: String = "",
        val source: String = "",
        val genre: String = "",
        val group: String = "",
        val studio: String = "",
    )

    private fun getExclusions(type: String, inputList: List<String>): String {
        return inputList.withIndex().joinToString(separator = "&") {
            "filter[$type][${it.index}][id]=${it.value}&filter[$type][${it.index}][opr]=exclude"
        }
    }

    internal fun getSearchParameters(filters: AnimeFilterList): FilterSearchParams {
        if (filters.isEmpty()) return FilterSearchParams()

        val type: String = getExclusions(
            "type",
            filters.filterIsInstance<TypeFilter>()
                .first()
                .state.mapNotNull { format ->
                    if (!format.state) {
                        MarinMoeFiltersData.types.find { it.first == format.name }!!.second
                    } else { null }
                },
        )

        val status: String = getExclusions(
            "status",
            filters.filterIsInstance<StatusFilter>()
                .first()
                .state.mapNotNull { format ->
                    if (!format.state) {
                        MarinMoeFiltersData.status.find { it.first == format.name }!!.second
                    } else { null }
                },
        )

        val contentRating: String = getExclusions(
            "content_rating",
            filters.filterIsInstance<ContentRatingFilter>()
                .first()
                .state.mapNotNull { format ->
                    if (!format.state) {
                        MarinMoeFiltersData.contentRating.find { it.first == format.name }!!.second
                    } else { null }
                },
        )

        val source: String = filters.filterIsInstance<SourceFilter>()
            .first()
            .state.mapNotNull { format ->
                if (format.state) {
                    MarinMoeFiltersData.source.find { it.first == format.name }!!.second
                } else { null }
            }.withIndex().joinToString(separator = "&") {
                "filter[source][${it.index}][id]=${it.value}&filter[source][${it.index}][opr]=include"
            }

        val genre: String = filters.filterIsInstance<GenreFilter>()
            .first()
            .state.mapNotNull { format ->
                if (format.state) {
                    MarinMoeFiltersData.genre.find { it.first == format.name }!!.second
                } else { null }
            }.withIndex().joinToString(separator = "&") {
                "filter[genre][${it.index}][id]=${it.value}&filter[genre][${it.index}][opr]=include"
            }

        return FilterSearchParams(
            filters.asQueryPart<SortFilter>(),
            type,
            status,
            contentRating,
            source,
            genre,
            filters.asQueryPart<GroupFilter>(),
            filters.asQueryPart<StudioFilter>(),
        )
    }

    private object MarinMoeFiltersData {
        val sort = arrayOf(
            Pair("A to Z", "az-a"),
            Pair("Z to A", "az-d"),
            Pair("Earliest Released", "rel-a"),
            Pair("Latest Released", "rel-d"),
            Pair("First Added", "add-a"),
            Pair("Last Added", "add-d"),
            Pair("Least Popular", "vtt-a"),
            Pair("Most Popular", "vtt-d"),
            Pair("Least Popular Today", "vdy-a"),
            Pair("Most Popular Today", "vdy-d"),
            Pair("Least Popular This Week", "vwk-a"),
            Pair("Most Popular This Week", "vwk-d"),
            Pair("Least Popular This Month", "vmt-a"),
            Pair("Most Popular This Month", "vmt-d"),
            Pair("Least Popular This Year", "vyr-a"),
            Pair("Most Popular This Year", "vyr-d"),
        )

        val types = arrayOf(
            Pair("Unknown", "1"),
            Pair("TV Series", "2"),
            Pair("OVA", "3"),
            Pair("Movie", "4"),
            Pair("Web", "5"),
            Pair("Music Video", "6"),
            Pair("TV Special", "7"),
            Pair("Other", "8"),
        )

        val status = arrayOf(
            Pair("Unknown", "1"),
            Pair("Ongoing", "2"),
            Pair("Completed", "3"),
            Pair("Stalled", "4"),
        )

        val contentRating = arrayOf(
            Pair("Unknown", "1"),
            Pair("PG - Children", "2"),
            Pair("PG-13 - Teens 13 or older", "3"),
            Pair("R+ - Mild Nudity", "4"),
            Pair("R - 17+ (violence & profanity)", "5"),
            Pair("Rx - Hentai", "6"),
            Pair("G - All Ages", "7"),
        )

        val source = arrayOf(
            Pair("Blu-ray", "5"),
            Pair("DVD", "4"),
            Pair("LD", "8"),
            Pair("N/A", "1"),
            Pair("TV", "2"),
            Pair("VCD", "7"),
            Pair("VHS", "6"),
            Pair("Web", "3"),
        )

        val genre = arrayOf(
            Pair("Action", "1"),
            Pair("Adult Cast", "55"),
            Pair("Adventure", "15"),
            Pair("Anthropomorphic", "59"),
            Pair("Avant Garde", "34"),
            Pair("Award Winning", "74"),
            Pair("Boys Love", "35"),
            Pair("CGDCT", "54"),
            Pair("Childcare", "64"),
            Pair("Combat Sports", "76"),
            Pair("Comedy", "8"),
            Pair("Crossdressing", "77"),
            Pair("Delinquents", "69"),
            Pair("Demons", "28"),
            Pair("Detective", "56"),
            Pair("Drama", "9"),
            Pair("Ecchi", "4"),
            Pair("Educational", "73"),
            Pair("Fantasy", "6"),
            Pair("Gag Humor", "52"),
            Pair("Game", "11"),
            Pair("Girls Love", "31"),
            Pair("Gore", "67"),
            Pair("Gourmet", "39"),
            Pair("Harem", "2"),
            Pair("High Stakes Game", "41"),
            Pair("Historical", "27"),
            Pair("Horror", "24"),
            Pair("Idols (Female)", "49"),
            Pair("Idols (Male)", "62"),
            Pair("Isekai", "48"),
            Pair("Iyashikei", "45"),
            Pair("Kids", "37"),
            Pair("Love Polygon", "68"),
            Pair("Magic", "16"),
            Pair("Magical Sex Shift", "53"),
            Pair("Mahou Shoujo", "50"),
            Pair("Martial Arts", "30"),
            Pair("Mecha", "19"),
            Pair("Medical", "65"),
            Pair("Military", "18"),
            Pair("Music", "23"),
            Pair("Mystery", "33"),
            Pair("Mythology", "58"),
            Pair("Organized Crime", "61"),
            Pair("Otaku Culture", "43"),
            Pair("Parody", "17"),
            Pair("Performing Arts", "63"),
            Pair("Police", "36"),
            Pair("Psychological", "14"),
            Pair("Racing", "75"),
            Pair("Reincarnation", "51"),
            Pair("Reverse Harem", "72"),
            Pair("Romance", "10"),
            Pair("Romantic Subtext", "57"),
            Pair("Samurai", "40"),
            Pair("School", "7"),
            Pair("Sci-Fi", "22"),
            Pair("Showbiz", "44"),
            Pair("Slice of Life", "13"),
            Pair("Space", "26"),
            Pair("Sports", "25"),
            Pair("Strategy Game", "46"),
            Pair("Super Power", "29"),
            Pair("Supernatural", "3"),
            Pair("Survival", "71"),
            Pair("Suspense", "32"),
            Pair("Team Sports", "60"),
            Pair("Time Travel", "47"),
            Pair("Vampire", "5"),
            Pair("Video Game", "70"),
            Pair("Visual Arts", "66"),
            Pair("Workplace", "42"),
        )

        val groups = arrayOf(
            Pair("All", ""),
            Pair("-__-`", "279"),
            Pair("-.-", "221"),
            Pair("Abstinence", "324"),
            Pair("AC_", "71"),
            Pair("ADZ Subs", "116"),
            Pair("Afternoon Naps Empire", "62"),
            Pair("Almighty", "182"),
            Pair("Alt", "317"),
            Pair("Anime Noobs Fansubbers", "265"),
            Pair("Anime-4ever", "218"),
            Pair("Anime-Conan", "257"),
            Pair("Anime-Destiny", "155"),
            Pair("Anime-Empire", "281"),
            Pair("Anime-FanRips", "322"),
            Pair("Anime-Fury", "70"),
            Pair("Anime-Jiyuu", "264"),
            Pair("Anime-Supreme", "278"),
            Pair("anime4life.", "127"),
            Pair("AnimeBytes Remuxes", "94"),
            Pair("AnimeOne", "215"),
            Pair("AnimeSenshi Subs", "27"),
            Pair("AnimeYuki", "104"),
            Pair("Anonymous", "33"),
            Pair("Anonymous Russian Rippers", "224"),
            Pair("AOmundson", "35"),
            Pair("ARC", "111"),
            Pair("Aria", "99"),
            Pair("Arid", "86"),
            Pair("aRMX", "337"),
            Pair("aro", "334"),
            Pair("Asakura", "81"),
            Pair("asc3nsi0n", "234"),
            Pair("Asteroid", "339"),
            Pair("AtlasSubbed", "128"),
            Pair("Ayashii", "190"),
            Pair("AZ Fansubs", "247"),
            Pair("AZ Fansubs & Baka-Gaijin", "251"),
            Pair("B2E", "120"),
            Pair("Baaro", "242"),
            Pair("Baka-Gaijin & Detective Conan Files", "249"),
            Pair("BakaBT Remuxes", "105"),
            Pair("Bakahorizonsama", "172"),
            Pair("BananaBoat", "176"),
            Pair("Beatrice-Raws", "207"),
            Pair("Black Organization", "263"),
            Pair("BluDragon", "288"),
            Pair("BlurayDesuYo", "25"),
            Pair("bradosia", "133"),
            Pair("Bunny Hat Raw", "88"),
            Pair("C137", "237"),
            Pair("Cait-Sidhe", "277"),
            Pair("Cartoon-World", "150"),
            Pair("Catar", "37"),
            Pair("CBT", "217"),
            Pair("Chihiro-Fansubs", "7"),
            Pair("Chosensilver Remux", "138"),
            Pair("Chotab", "248"),
            Pair("CitadelofTheRaven", "113"),
            Pair("Clara", "6"),
            Pair("Cman21", "225"),
            Pair("Coalgirls", "11"),
            Pair("Cold Fusion", "125"),
            Pair("Cold Fusion & Baaro", "239"),
            Pair("coldhell", "29"),
            Pair("ColorMeSubbed", "167"),
            Pair("Commie", "60"),
            Pair("Commsei", "306"),
            Pair("cornbreadman", "117"),
            Pair("Crow", "130"),
            Pair("Cry", "316"),
            Pair("CsS", "326"),
            Pair("CUNNY", "274"),
            Pair("D.O.M.O.", "323"),
            Pair("DameDesuYo", "59"),
            Pair("DarkDream", "238"),
            Pair("darkfire68", "47"),
            Pair("Darkonius & wisperer", "286"),
            Pair("Datte13", "175"),
            Pair("deanzel", "54"),
            Pair("Detective Conan Translation Project", "246"),
            Pair("Detective Conan Translation Project & AZ Fansubs", "256"),
            Pair("Detective Conan Translation Project & Kienai-Niji", "269"),
            Pair("Detective Conan Translation Project & NazoNoKami", "270"),
            Pair("Detective Conan Translation Project & The Moonlighters", "260"),
            Pair("Deus EX Anima", "22"),
            Pair("DigitalPanic", "330"),
            Pair("DigitalSubs", "202"),
            Pair("Dknight", "34"),
            Pair("DmonHiro", "21"),
            Pair("Doki Fansubs", "4"),
            Pair("Doki Fansubs & Chihiro Fansubs", "13"),
            Pair("DorianHD", "318"),
            Pair("DorianHD & FoxesDen", "208"),
            Pair("Doutei Fansubs", "15"),
            Pair("Drag", "78"),
            Pair("drawn-reality", "156"),
            Pair("Dual Audio Empire", "132"),
            Pair("EightBit", "39"),
            Pair("Elysium Subs", "131"),
            Pair("EMBER", "206"),
            Pair("Enceladus", "82"),
            Pair("EncoderAnon", "299"),
            Pair("Encodergasm", "301"),
            Pair("entameSubs", "296"),
            Pair("Erai-raws", "151"),
            Pair("Exiled-Destiny", "61"),
            Pair("ExoDus", "112"),
            Pair("Explorer", "158"),
            Pair("eXterminator", "333"),
            Pair("Fansubber-ES", "115"),
            Pair("FFFpeeps", "1"),
            Pair("FFFpeeps & Interrobang", "152"),
            Pair("FFFpeeps & Kantai-Subs", "170"),
            Pair("FFFpeeps & Vivid Subs", "67"),
            Pair("Final8", "285"),
            Pair("Flamwenco", "173"),
            Pair("FLUX", "177"),
            Pair("Frostii & AnimeONE", "216"),
            Pair("Funnuraba Fansubs", "201"),
            Pair("Galator", "303"),
            Pair("Gekkostate", "137"),
            Pair("GHOST", "143"),
            Pair("ghostosenpai", "272"),
            Pair("Glenn", "169"),
            Pair("Glue", "164"),
            Pair("Godim", "186"),
            Pair("Godless-Orphan", "16"),
            Pair("Golosubs", "41"),
            Pair("Golumpa", "40"),
            Pair("good", "287"),
            Pair("Good Job! Media", "8"),
            Pair("Good Job! Media & Kaleido-subs", "275"),
            Pair("GotWoot Fansubs", "109"),
            Pair("Grim Ripper", "204"),
            Pair("Grim-F", "325"),
            Pair("gskumar", "101"),
            Pair("GST", "195"),
            Pair("GUDish", "165"),
            Pair("HachiRokuNiSanKyu", "304"),
            Pair("Hari-No-Ito", "266"),
            Pair("Hark0n", "63"),
            Pair("Harunatsu Fansubs", "14"),
            Pair("hchcsen", "228"),
            Pair("High Quality Releases", "292"),
            Pair("Holomux", "194"),
            Pair("HorribleSubs", "20"),
            Pair("hose", "184"),
            Pair("Hotaru", "12"),
            Pair("iAHD", "46"),
            Pair("If you don`t download this I will cry", "226"),
            Pair("IK-User", "179"),
            Pair("iKaos", "273"),
            Pair("Inka-Subs", "291"),
            Pair("InoBestGirl", "180"),
            Pair("Inverti", "148"),
            Pair("ITH", "145"),
            Pair("Iznjie Biznjie", "252"),
            Pair("jackie", "314"),
            Pair("joseole99", "280"),
            Pair("JPSDR", "297"),
            Pair("Judgment", "159"),
            Pair("Jumonji-Giri", "231"),
            Pair("JustAnotherRemux", "118"),
            Pair("JySzE", "157"),
            Pair("KaizouFansubs", "250"),
            Pair("Kaleido-subs", "189"),
            Pair("Kaleido-subs & Flax Subs", "124"),
            Pair("Kaleido-subs & Scyrous", "129"),
            Pair("Kametsu", "45"),
            Pair("Kantai-Subs", "139"),
            Pair("karios", "230"),
            Pair("Karma Rips", "32"),
            Pair("Kawaii", "327"),
            Pair("Kawaiika-Raws", "74"),
            Pair("Kaze no Koe Fansubs", "245"),
            Pair("kBaraka", "233"),
            Pair("KH", "50"),
            Pair("Kienai", "254"),
            Pair("Kienai-Niji & AZ FAnsubs", "255"),
            Pair("Kira_SEV", "55"),
            Pair("Kira-Fansub", "36"),
            Pair("Kiriya", "135"),
            Pair("KiteSeekers & Kira-Fansub", "227"),
            Pair("KiteSeekers & Licca Fansubs", "229"),
            Pair("KOSMOS", "310"),
            Pair("Koten Gars", "102"),
            Pair("KOTEX", "23"),
            Pair("kuchikirukia", "43"),
            Pair("Kulot", "282"),
            Pair("Kyozoku", "259"),
            Pair("Laidback", "107"),
            Pair("Last Resort Encodes", "103"),
            Pair("Late Night Snack", "18"),
            Pair("Lazy Lily Subs", "126"),
            Pair("Legion", "319"),
            Pair("Lisata598", "134"),
            Pair("Live-eviL", "210"),
            Pair("LostYears", "136"),
            Pair("Lulu", "140"),
            Pair("MaskedCape", "290"),
            Pair("Mazui", "26"),
            Pair("MeruMeruSubs", "193"),
            Pair("MetalicBox", "178"),
            Pair("Metaljerk", "209"),
            Pair("Mew", "76"),
            Pair("Migoto Fansubs", "144"),
            Pair("Moodkiller", "44"),
            Pair("Moodkiller & Scyrous", "56"),
            Pair("Moozzi2", "294"),
            Pair("motbob", "77"),
            Pair("mottoj-anime", "28"),
            Pair("MoyaiSubs", "196"),
            Pair("Mysteria", "38"),
            Pair("NanDesuKa?", "284"),
            Pair("NazoNoKami", "243"),
            Pair("NazoNoKami & KaizouFansubs", "261"),
            Pair("NC-Raws", "315"),
            Pair("neko-raws", "213"),
            Pair("NekomimiTeikoku", "187"),
            Pair("neo1024", "97"),
            Pair("Nep Blanc", "2"),
            Pair("Netaro", "235"),
            Pair("NetflixSucks", "183"),
            Pair("NeutralHatred", "96"),
            Pair("nielsen145", "123"),
            Pair("nImEHuntetD", "66"),
            Pair("Nineball", "305"),
            Pair("Nofunloli", "191"),
            Pair("Noms", "197"),
            Pair("NovaWorks", "185"),
            Pair("Nuke Fansubs", "79"),
            Pair("Nyanpasu Subs", "160"),
            Pair("Okay-Subs", "295"),
            Pair("Orphan", "289"),
            Pair("Orphan & macros74", "320"),
            Pair("owowo", "222"),
            Pair("oZanderr", "205"),
            Pair("OZC Anime", "84"),
            Pair("Patjantess", "214"),
            Pair("Pineapple Salad", "89"),
            Pair("PiPoPaHd", "302"),
            Pair("pls", "58"),
            Pair("Pog42", "203"),
            Pair("Polished Subs", "90"),
            Pair("pooookie", "313"),
            Pair("Puto", "241"),
            Pair("pyroneko", "17"),
            Pair("Quetzal", "181"),
            Pair("Quickie", "332"),
            Pair("Raizel", "91"),
            Pair("Rakuda", "95"),
            Pair("RASETSU", "108"),
            Pair("Real-Anime Xtreme", "338"),
            Pair("ReDone-Subs", "73"),
            Pair("ReinForce", "171"),
            Pair("Reito`s Rockin Rips", "311"),
            Pair("RemuxBobP", "42"),
            Pair("Retrofit", "98"),
            Pair("rickyhorror", "75"),
            Pair("Rising Sun", "51"),
            Pair("RMX", "53"),
            Pair("Robonation", "223"),
            Pair("Rom & Rem", "65"),
            Pair("Saizen Fansubs", "200"),
            Pair("Saizen-Fansubs & Ignition-One", "335"),
            Pair("SakuraCircle", "5"),
            Pair("SallySubs", "30"),
            Pair("samaritan", "211"),
            Pair("SchwingBoner", "276"),
            Pair("Scriptum", "119"),
            Pair("Scyrous", "52"),
            Pair("Sea of Serenity Subs", "121"),
            Pair("Serenae", "166"),
            Pair("ShadyCrab", "92"),
            Pair("Shimatta", "154"),
            Pair("Shindou-Anime", "298"),
            Pair("Shining Fansubs", "262"),
            Pair("ShiraRaminz", "192"),
            Pair("Shirase", "174"),
            Pair("Shirσ", "93"),
            Pair("Shisukon", "80"),
            Pair("Smoke", "49"),
            Pair("smoon", "110"),
            Pair("SmugCat", "268"),
            Pair("SmugMug", "141"),
            Pair("SNSbu", "24"),
            Pair("Solar Fansubs", "329"),
            Pair("solaufein", "232"),
            Pair("SSP-Corp", "69"),
            Pair("Static-Subs & AnimeYuki", "336"),
            Pair("Static-Subs & Eclipse Productions", "308"),
            Pair("SubsPlease", "48"),
            Pair("Suiri Otaku", "271"),
            Pair("Sushi Fansubs", "236"),
            Pair("sxales", "114"),
            Pair("Tamaya", "198"),
            Pair("Tap24", "72"),
            Pair("The Moonlighters", "244"),
            Pair("The0x539", "212"),
            Pair("Thighs", "312"),
            Pair("Tipota Encodes", "293"),
            Pair("tlacatlc6", "19"),
            Pair("ToTheGlory Anime", "267"),
            Pair("Tsundere Rips", "3"),
            Pair("TV-Nihon", "149"),
            Pair("Underwater", "100"),
            Pair("Unlimited Translation Works", "64"),
            Pair("Unlimited Translation Works & Mazui", "188"),
            Pair("unwanteddubfan", "83"),
            Pair("Ureshii", "258"),
            Pair("Vanilla", "309"),
            Pair("Virus123", "168"),
            Pair("Vivid Subs", "220"),
            Pair("Vodes", "162"),
            Pair("Waku", "57"),
            Pair("Wasurenai Fansubs", "9"),
            Pair("Wasurenai Fansubs & Anime-Himitsu", "10"),
            Pair("WAVE", "240"),
            Pair("WhoBeDaPlaya", "146"),
            Pair("WhyNot?", "68"),
            Pair("WIP", "300"),
            Pair("Wyse", "122"),
            Pair("Xanth", "321"),
            Pair("xCryptic", "199"),
            Pair("xKrptonicz", "163"),
            Pair("Xonline", "85"),
            Pair("xPearse", "307"),
            Pair("xxon", "161"),
            Pair("YA", "328"),
            Pair("Yameii", "219"),
            Pair("Yami-Fansubs", "253"),
            Pair("YamiWheeler", "106"),
            Pair("Yellow-Flash", "331"),
            Pair("Yousoro", "142"),
            Pair("YURI", "87"),
            Pair("Z4ST1N", "31"),
            Pair("zangafan", "153"),
            Pair("ZetaRebel", "147"),
            Pair("Zurako Subs", "283"),
        )

        val studios = arrayOf(
            Pair("All", ""),
            Pair("3xCube", "432"),
            Pair("4Kids Entertainment", "340"),
            Pair("5pb.", "465"),
            Pair("81 Produce", "50"),
            Pair("8bit", "134"),
            Pair("A-1 Pictures", "3"),
            Pair("A-Line", "620"),
            Pair("A-Real", "590"),
            Pair("A.C.G.T.", "486"),
            Pair("A3", "455"),
            Pair("ABC Animation", "160"),
            Pair("ABC Frontier", "652"),
            Pair("ADK Emotions", "376"),
            Pair("ADK Marketing Solutions", "506"),
            Pair("ADV Films", "249"),
            Pair("AG-ONE", "266"),
            Pair("Age", "303"),
            Pair("Age Global Networks", "72"),
            Pair("Ai Addiction", "551"),
            Pair("AIC", "10"),
            Pair("AIC ASTA", "277"),
            Pair("AIC Build", "118"),
            Pair("AIC PLUS+", "393"),
            Pair("AIC Spirits", "30"),
            Pair("Ajia-Do", "156"),
            Pair("AKABEiSOFT2", "66"),
            Pair("Akatsuki", "27"),
            Pair("Akita Shoten", "147"),
            Pair("Alice", "598"),
            Pair("Amber Film Works", "318"),
            Pair("AMG Entertainment", "586"),
            Pair("AMG MUSIC", "480"),
            Pair("Amusement Media Academy", "471"),
            Pair("Anchor", "687"),
            Pair("animate Film", "333"),
            Pair("Animatic", "218"),
            Pair("Animation Do", "224"),
            Pair("Animatsu Entertainment", "267"),
            Pair("Animax", "299"),
            Pair("Anime Midstream", "388"),
            Pair("Anime R", "520"),
            Pair("AnimEigo", "328"),
            Pair("Aniplex", "5"),
            Pair("Aniplex of America", "173"),
            Pair("Aoni Entertainment", "570"),
            Pair("APDREAM", "398"),
            Pair("Apollon", "627"),
            Pair("APPP", "323"),
            Pair("AQUA ARIS", "373"),
            Pair("Aquamarine", "540"),
            Pair("AQUAPLUS", "470"),
            Pair("arma bianca", "600"),
            Pair("Arms", "330"),
            Pair("Artist Management Office", "385"),
            Pair("Artland", "578"),
            Pair("Artmic", "567"),
            Pair("Arvo Animation", "436"),
            Pair("Asahi Broadcasting", "136"),
            Pair("Asahi Production", "153"),
            Pair("Asatsu DK", "181"),
            Pair("ASCII Media Works", "44"),
            Pair("Ashi Production", "286"),
            Pair("Ashi Productions", "684"),
            Pair("ASK Animation Studio", "566"),
            Pair("Asmik Ace", "22"),
            Pair("asread.", "362"),
            Pair("AT-X", "55"),
            Pair("Atelier Musa", "260"),
            Pair("AtelierPontdarc", "426"),
            Pair("Audio Tanaka", "306"),
            Pair("Avex Entertainment", "220"),
            Pair("Avex Pictures", "99"),
            Pair("Avex Technologies", "342"),
            Pair("AXsiZ", "111"),
            Pair("AZ Creative", "381"),
            Pair("B.CMAY PICTURES", "670"),
            Pair("Bakken Record", "685"),
            Pair("Bandai", "92"),
            Pair("Bandai Channel", "285"),
            Pair("Bandai Entertainment", "176"),
            Pair("Bandai Namco Arts", "229"),
            Pair("Bandai Namco Entertainment", "93"),
            Pair("Bandai Namco Filmworks", "563"),
            Pair("Bandai Namco Games", "253"),
            Pair("Bandai Namco Live Creative", "198"),
            Pair("Bandai Namco Music Live", "564"),
            Pair("Bandai Namco Pictures", "354"),
            Pair("Bandai Spirits", "307"),
            Pair("Bandai Visual", "91"),
            Pair("Banpresto", "519"),
            Pair("Barnum Studio", "56"),
            Pair("Bee Media", "377"),
            Pair("Bee Train", "349"),
            Pair("Being", "645"),
            Pair("Bergamo", "602"),
            Pair("Bestack", "29"),
            Pair("Beyond C.", "655"),
            Pair("Bibury Animation Studios", "240"),
            Pair("Big West", "150"),
            Pair("BIGLOBE", "265"),
            Pair("bilibili", "128"),
            Pair("Bit grooove promotion", "184"),
            Pair("Bit Promotion", "496"),
            Pair("Blade", "548"),
            Pair("BloomZ", "584"),
            Pair("Bones", "201"),
            Pair("Bouncy", "374"),
            Pair("Brain's Base", "222"),
            Pair("Bridge", "309"),
            Pair("Broccoli", "523"),
            Pair("BS Asahi", "601"),
            Pair("BS Fuji", "96"),
            Pair("BS Japan", "138"),
            Pair("BS NTV", "453"),
            Pair("BS-TBS", "34"),
            Pair("BS11", "24"),
            Pair("Bulls Eye", "231"),
            Pair("Bushiroad", "107"),
            Pair("Bushiroad Creative", "642"),
            Pair("Bushiroad Move", "407"),
            Pair("Bushiroad Music", "352"),
            Pair("C & I entertainment", "414"),
            Pair("C-one", "395"),
            Pair("C-Station", "279"),
            Pair("C2C", "357"),
            Pair("CA-Cygames Anime Fund", "257"),
            Pair("CBC Television", "400"),
            Pair("CD Projekt Red", "632"),
            Pair("Central Park Media", "334"),
            Pair("Chaos Project", "469"),
            Pair("chara-ani.com", "228"),
            Pair("Children's Playground Entertainment", "415"),
            Pair("Christmas Holly", "418"),
            Pair("Chugai Mining", "87"),
            Pair("Chukyo TV Broadcasting", "449"),
            Pair("CIC", "532"),
            Pair("Cloud Hearts", "679"),
            Pair("Cloud22", "283"),
            Pair("CloverWorks", "256"),
            Pair("Colored Pencil Animation", "375"),
            Pair("Colored Pencil Animation Japan", "621"),
            Pair("comico", "413"),
            Pair("CoMix Wave Films", "438"),
            Pair("Connect", "2"),
            Pair("Contents Seed", "25"),
            Pair("Cosmic Ray", "195"),
            Pair("Cospa", "310"),
            Pair("Creators in Pack", "281"),
            Pair("Creek", "603"),
            Pair("CREi", "671"),
            Pair("Crest", "560"),
            Pair("Cromea", "26"),
            Pair("Crunchyroll", "171"),
            Pair("Crunchyroll SC Anime Fund", "162"),
            Pair("Culture Entertainment", "658"),
            Pair("Culture Publishers", "482"),
            Pair("CyberAgent", "443"),
            Pair("Cyclone Graphics", "661"),
            Pair("Cygames", "514"),
            Pair("CygamesPictures", "512"),
            Pair("d-rights", "526"),
            Pair("D-techno", "188"),
            Pair("D.N. Dream Partners", "338"),
            Pair("Daiichi Shokai", "382"),
            Pair("Daiichikosho", "527"),
            Pair("Daume", "163"),
            Pair("David Production", "410"),
            Pair("DAX Production", "33"),
            Pair("Days", "640"),
            Pair("Delfi Sound", "70"),
            Pair("DeNA", "424"),
            Pair("Dentsu", "121"),
            Pair("Diomedéa", "230"),
            Pair("Discotek Media", "179"),
            Pair("DIVE II Entertainment", "97"),
            Pair("DLE", "127"),
            Pair("DMM Music", "234"),
            Pair("DMM pictures", "313"),
            Pair("DMM.com", "282"),
            Pair("DMM.futureworks", "344"),
            Pair("Docomo Anime Store", "73"),
            Pair("Doga Kobo", "146"),
            Pair("Dongwoo A&E", "433"),
            Pair("DR Movie", "547"),
            Pair("Dream Force", "689"),
            Pair("Dream Shift", "339"),
            Pair("Drecom", "280"),
            Pair("Drive", "589"),
            Pair("dugout", "537"),
            Pair("Dwango", "428"),
            Pair("E&G Films", "488"),
            Pair("Earth Star Entertainment", "158"),
            Pair("eBooK Initiative Japan", "148"),
            Pair("Egg Firm", "236"),
            Pair("EKACHI EPILKA", "269"),
            Pair("Eleven Arts", "423"),
            Pair("ELF-IN", "383"),
            Pair("EMT Squared", "356"),
            Pair("Encourage Films", "463"),
            Pair("ENGI", "95"),
            Pair("ensky", "650"),
            Pair("Enterbrain", "133"),
            Pair("Epicross", "641"),
            Pair("eStream", "550"),
            Pair("Eswood", "219"),
            Pair("Exa International", "452"),
            Pair("Exit Tunes", "141"),
            Pair("Eye Move", "336"),
            Pair("Ezόla", "577"),
            Pair("F.M.F", "498"),
            Pair("f4samurai", "427"),
            Pair("FBC", "458"),
            Pair("feel.", "40"),
            Pair("Felix Film", "341"),
            Pair("feng", "302"),
            Pair("Fields", "481"),
            Pair("flaggs", "596"),
            Pair("FLAGSHIP LINE", "444"),
            Pair("Flatiron Film Company", "475"),
            Pair("Flex Comix", "319"),
            Pair("flying DOG", "116"),
            Pair("Forecast Communications", "372"),
            Pair("Fosun Entertainment Japan", "508"),
            Pair("Front Line", "494"),
            Pair("Front Wing", "353"),
            Pair("Frontier Works", "86"),
            Pair("Fuji Creative", "492"),
            Pair("Fuji TV", "122"),
            Pair("Fujimi Shobo", "105"),
            Pair("Fujipacific Music", "157"),
            Pair("Fujishouji", "623"),
            Pair("Funimation", "170"),
            Pair("Furyu", "100"),
            Pair("Futabasha", "592"),
            Pair("GAGA", "287"),
            Pair("Gaina", "616"),
            Pair("Gainax", "300"),
            Pair("Gallop", "404"),
            Pair("Gambit", "435"),
            Pair("GANSIS", "210"),
            Pair("GDH", "484"),
            Pair("Geek Pictures", "673"),
            Pair("GEEK TOYS", "513"),
            Pair("Genco", "14"),
            Pair("Geneon Entertainment USA", "196"),
            Pair("Geneon Universal Entertainment", "193"),
            Pair("Geno Studio", "431"),
            Pair("Gentosha Comics", "672"),
            Pair("GIFTanimation", "462"),
            Pair("Gigno Systems", "487"),
            Pair("Ginga Ya", "531"),
            Pair("Global Solutions", "583"),
            Pair("Glovision", "216"),
            Pair("Gonzo", "131"),
            Pair("Good Smile Company", "119"),
            Pair("Good Smile Film", "241"),
            Pair("GRANTdesign", "633"),
            Pair("Graphinica", "23"),
            Pair("Gree", "143"),
            Pair("GREE Entertainment", "454"),
            Pair("Grooove", "98"),
            Pair("Group TAC", "295"),
            Pair("GYAO!", "114"),
            Pair("Hakuhodo", "609"),
            Pair("Hakuhodo DY Media Partners", "94"),
            Pair("Hakuhodo DY Music & Pictures", "77"),
            Pair("Hakusensha", "69"),
            Pair("Hal Film Maker", "263"),
            Pair("Half H.P Studio", "21"),
            Pair("Haoliners Animation League", "466"),
            Pair("Happinet", "273"),
            Pair("Happinet Phantom Studios", "576"),
            Pair("Happinet Pictures", "232"),
            Pair("Harappa", "591"),
            Pair("Harmony Gold", "667"),
            Pair("Hayabusa Film", "557"),
            Pair("Hayakawa Shobou", "472"),
            Pair("Heart Company", "358"),
            Pair("Highlights Entertainment", "656"),
            Pair("Hobby Japan", "140"),
            Pair("Hobibox", "130"),
            Pair("Hochi Shimbun", "610"),
            Pair("Hokkaido Cultural Broadcasting", "541"),
            Pair("Hoods Entertainment", "322"),
            Pair("HoriPro International", "646"),
            Pair("HORNETS", "554"),
            Pair("Hotline", "437"),
            Pair("Houbunsha", "42"),
            Pair("I Will", "518"),
            Pair("i0+", "58"),
            Pair("ibis Capital Partners", "542"),
            Pair("Ichijinsha", "110"),
            Pair("Idea Factory", "411"),
            Pair("Idol", "664"),
            Pair("ILCA", "380"),
            Pair("Illumitoon Entertainment", "390"),
            Pair("Imagica", "326"),
            Pair("IMAGICA Lab.", "399"),
            Pair("Imagin", "630"),
            Pair("Imagine", "255"),
            Pair("INCS toenter", "363"),
            Pair("Infinite", "166"),
            Pair("ING", "335"),
            Pair("INSPION Edge", "676"),
            Pair("IRMA LA DOUCE", "614"),
            Pair("J.C.Staff", "13"),
            Pair("Japan Home Video", "315"),
            Pair("jeux d'eau", "456"),
            Pair("Jinnan Studio", "359"),
            Pair("JR East Marketing & Communications", "204"),
            Pair("JTB Entertainment", "155"),
            Pair("JTB Next Creation", "270"),
            Pair("Jumondo", "41"),
            Pair("K contents", "683"),
            Pair("K-Factory", "666"),
            Pair("Kadokawa", "185"),
            Pair("Kadokawa Animation", "209"),
            Pair("Kadokawa Contents Gate", "206"),
            Pair("Kadokawa Media House", "51"),
            Pair("Kadokawa Pictures Japan", "102"),
            Pair("Kadokawa Pictures USA", "421"),
            Pair("Kadokawa Shoten", "53"),
            Pair("Kamikaze Douga", "429"),
            Pair("Kanade Creative", "604"),
            Pair("Kaname Productions", "665"),
            Pair("Kanetsu Co. LTD.", "88"),
            Pair("Kanetsu Investment", "417"),
            Pair("Kanon Sound", "129"),
            Pair("Kansai Telecasting", "124"),
            Pair("Karaku", "308"),
            Pair("Khara", "533"),
            Pair("Kids Station", "332"),
            Pair("Kigumi", "503"),
            Pair("Kill Time Communication", "677"),
            Pair("Kinema Citrus", "215"),
            Pair("King Records", "117"),
            Pair("Kinoshita Group Holdings", "45"),
            Pair("Kinoshita Koumuten", "659"),
            Pair("Kitty Films", "626"),
            Pair("KLab", "606"),
            Pair("KlockWorx", "47"),
            Pair("Kodansha", "80"),
            Pair("Koei Tecmo Games", "608"),
            Pair("Konami", "387"),
            Pair("Konami Digital Entertainment", "657"),
            Pair("Kotobukiya", "535"),
            Pair("KSS", "226"),
            Pair("Kyoraku Industrial Holdings", "123"),
            Pair("Kyoto Animation", "137"),
            Pair("Lantis", "64"),
            Pair("Lapin Track", "419"),
            Pair("Laulea Works", "597"),
            Pair("Lawson", "36"),
            Pair("Lawson Entertainment", "594"),
            Pair("Lawson HMV Entertainment", "291"),
            Pair("Lay-duce", "312"),
            Pair("Legs", "574"),
            Pair("Lerche", "12"),
            Pair("LEVELS", "559"),
            Pair("Liber", "674"),
            Pair("Liber Entertainment", "499"),
            Pair("LIDENFILMS", "101"),
            Pair("LIDENFILMS Kyoto Studio", "182"),
            Pair("Live Viewing Japan", "553"),
            Pair("LOGIC&MAGIC", "678"),
            Pair("Lucent Pictures Entertainment", "408"),
            Pair("Lucky Paradise", "422"),
            Pair("m.o.e.", "491"),
            Pair("M.S.C", "612"),
            Pair("Mad Box", "207"),
            Pair("Madhouse", "7"),
            Pair("Mag Garden", "416"),
            Pair("MAGES.", "186"),
            Pair("Magic Bus", "246"),
            Pair("Magic Capsule", "16"),
            Pair("Magnet", "161"),
            Pair("Maho Film", "384"),
            Pair("Maiden Japan", "178"),
            Pair("Mainichi Broadcasting System", "115"),
            Pair("Manglobe", "329"),
            Pair("MAPPA", "208"),
            Pair("Marui Group", "460"),
            Pair("Marvelous", "258"),
            Pair("Marvelous AQL", "71"),
            Pair("Marvy Jack", "631"),
            Pair("Media Blasters", "177"),
            Pair("Media Factory", "65"),
            Pair("MediaNet", "139"),
            Pair("MediaNet Pictures", "575"),
            Pair("Medicos Entertainment", "59"),
            Pair("Mellow Head", "529"),
            Pair("Memory-Tech", "192"),
            Pair("Micro House", "588"),
            Pair("Micro Magazine Publishing", "409"),
            Pair("Midorimatsu", "549"),
            Pair("Milky Cartoon", "628"),
            Pair("Millepensee", "239"),
            Pair("Mippei Eigeki Kiryuukan", "325"),
            Pair("Mirai-Kojo", "585"),
            Pair("Mixer", "681"),
            Pair("Mobcast", "221"),
            Pair("Movic", "43"),
            Pair("Muse Communication", "611"),
            Pair("Music Brains", "546"),
            Pair("Music Ray'n", "476"),
            Pair("MusicRay’n", "593"),
            Pair("My Theater D.D.", "348"),
            Pair("Myrica Music", "351"),
            Pair("Nagoya Broadcasting Network", "183"),
            Pair("Nakamura Production", "669"),
            Pair("NAZ", "618"),
            Pair("NBCUniversal Entertainment Japan", "57"),
            Pair("NEC Avenue", "622"),
            Pair("Nelke Planning", "397"),
            Pair("Nelvana", "292"),
            Pair("NetEase", "507"),
            Pair("NewGin", "528"),
            Pair("Nexus", "347"),
            Pair("NHK", "244"),
            Pair("NHK Enterprises", "386"),
            Pair("NHK-BS2", "569"),
            Pair("NichiNare", "346"),
            Pair("Nichion", "39"),
            Pair("Nihon Ad Systems", "174"),
            Pair("Nihon Falcom", "680"),
            Pair("Nikkatsu", "561"),
            Pair("Nippon Animation", "311"),
            Pair("Nippon Columbia", "46"),
            Pair("Nippon Cultural Broadcasting", "446"),
            Pair("Nippon Television Music", "168"),
            Pair("Nippon Television Network", "52"),
            Pair("NIS America, Inc.", "172"),
            Pair("Nitroplus", "202"),
            Pair("Nomad", "648"),
            Pair("Notes", "67"),
            Pair("Nozomi Entertainment", "180"),
            Pair("NTT Docomo", "199"),
            Pair("NTT Plala", "217"),
            Pair("Nut", "132"),
            Pair("NYAV Post", "243"),
            Pair("Office ENDLESS", "366"),
            Pair("Office Nobu", "582"),
            Pair("Okuruto Noboru", "233"),
            Pair("OLM", "225"),
            Pair("OLM Team Yoshioka", "515"),
            Pair("Omnibus Japan", "301"),
            Pair("Orange", "145"),
            Pair("Ordet", "108"),
            Pair("Overlap", "396"),
            Pair("OZ", "511"),
            Pair("P.A. Works", "164"),
            Pair("P.I.C.S.", "524"),
            Pair("Passione", "324"),
            Pair("Pb Animation Co. Ltd.", "638"),
            Pair("Pia", "617"),
            Pair("Pierrot", "625"),
            Pair("Pierrot Plus", "321"),
            Pair("Pine Jam", "84"),
            Pair("Pioneer LDC", "288"),
            Pair("Platinum Vision", "516"),
            Pair("Plus One", "668"),
            Pair("Polygon Pictures", "536"),
            Pair("Pony Canyon", "32"),
            Pair("Pony Canyon Enterprise", "112"),
            Pair("Ponycan USA", "211"),
            Pair("Poplar Publishing", "644"),
            Pair("PPP", "248"),
            Pair("PRA", "227"),
            Pair("Production +h.", "521"),
            Pair("Production Ace", "643"),
            Pair("Production I.G", "31"),
            Pair("Production IMS", "20"),
            Pair("Production Reed", "142"),
            Pair("Project No.9", "4"),
            Pair("Q-Tec", "135"),
            Pair("Quad", "501"),
            Pair("Quaras", "509"),
            Pair("RAB Aomori Broadcasting", "167"),
            Pair("Radio Osaka", "60"),
            Pair("Radix", "468"),
            Pair("Raku High Student Council", "477"),
            Pair("Rakuonsha", "212"),
            Pair("Rakuten", "579"),
            Pair("RAY", "37"),
            Pair("Remic", "305"),
            Pair("Revoroot", "297"),
            Pair("Rialto Entertainment", "534"),
            Pair("Rondo Robe", "278"),
            Pair("Ryukyu Asahi Broadcasting", "394"),
            Pair("Saber Links", "675"),
            Pair("Saetta", "558"),
            Pair("Sakura Create", "402"),
            Pair("Sammy", "187"),
            Pair("Sanrio", "474"),
            Pair("SANZIGEN", "144"),
            Pair("Satelight", "149"),
            Pair("SB Creative", "237"),
            Pair("Scarlet", "510"),
            Pair("Science SARU", "420"),
            Pair("Scooter Films", "539"),
            Pair("Sega", "565"),
            Pair("Seikaisha", "290"),
            Pair("Sentai Filmworks", "169"),
            Pair("Seven", "639"),
            Pair("Seven Arcs", "451"),
            Pair("Seven Stone Entertainment", "450"),
            Pair("Shaft", "223"),
            Pair("Shelty", "314"),
            Pair("Shenying Animation", "493"),
            Pair("Shin-Ei Animation", "81"),
            Pair("Shinchosha", "660"),
            Pair("Shirogumi", "364"),
            Pair("Shochiku", "152"),
            Pair("Shochiku Music Publishing", "406"),
            Pair("Shogakukan", "35"),
            Pair("Shogakukan Music & Digital Entertainment", "629"),
            Pair("Shogakukan-Shueisha Productions", "369"),
            Pair("Shout! Factory", "268"),
            Pair("Showgate", "62"),
            Pair("Shueisha", "8"),
            Pair("Shufunotomo", "653"),
            Pair("Shuka", "405"),
            Pair("Signal.MD", "447"),
            Pair("Silver", "304"),
            Pair("SILVER LINK.", "1"),
            Pair("Sky Perfect Communications", "483"),
            Pair("Slow Curve", "365"),
            Pair("SME Visual Works", "545"),
            Pair("Smiral Animation", "556"),
            Pair("Soft Garage", "615"),
            Pair("SoftBank Creative", "6"),
            Pair("SoftX", "490"),
            Pair("Sogo Vision", "293"),
            Pair("Sola Digital Arts", "467"),
            Pair("Sonilude", "262"),
            Pair("Sony Music Communications", "48"),
            Pair("Sony Music Entertainment", "109"),
            Pair("Sony Music Solutions", "245"),
            Pair("Sony PCL", "572"),
            Pair("Sony Pictures Entertainment", "85"),
            Pair("Sotsu", "54"),
            Pair("Sotsu Music Publishing", "485"),
            Pair("Sound Team Don Juan", "502"),
            Pair("Space Neko Company", "637"),
            Pair("Spectrum", "504"),
            Pair("Square Enix", "205"),
            Pair("Staple Entertainment", "607"),
            Pair("Starchild Records", "15"),
            Pair("Stardust Promotion", "113"),
            Pair("Starry Cube", "587"),
            Pair("Straight Edge", "214"),
            Pair("Stray Cats", "635"),
            Pair("Studio 3Hz", "259"),
            Pair("Studio 4°C", "654"),
            Pair("Studio A-CAT", "370"),
            Pair("Studio Bind", "235"),
            Pair("Studio Blanc", "379"),
            Pair("Studio Colorido", "430"),
            Pair("Studio Comet", "275"),
            Pair("Studio Deen", "19"),
            Pair("Studio Easter", "662"),
            Pair("Studio Fantasia", "251"),
            Pair("Studio Flad", "441"),
            Pair("Studio Flag", "525"),
            Pair("Studio Gokumi", "76"),
            Pair("Studio Gram", "343"),
            Pair("Studio Hibari", "63"),
            Pair("Studio Jack", "276"),
            Pair("Studio Jemi", "461"),
            Pair("Studio Junio", "505"),
            Pair("Studio Kai", "555"),
            Pair("Studio Kelmadick", "663"),
            Pair("Studio LAN", "624"),
            Pair("Studio Matrix", "316"),
            Pair("Studio Mausu", "213"),
            Pair("Studio Moriken", "331"),
            Pair("studio MOTHER", "517"),
            Pair("Studio Nue", "298"),
            Pair("Studio Palette", "442"),
            Pair("Studio Pastoral", "247"),
            Pair("Studio Pierrot", "75"),
            Pair("Studio Signpost", "412"),
            Pair("Studio Tulip", "489"),
            Pair("Studio Zain", "571"),
            Pair("Sublimation", "448"),
            Pair("Sumitomo", "83"),
            Pair("Sumzap", "538"),
            Pair("Sun TV", "682"),
            Pair("Sunny Side Up", "337"),
            Pair("Sunrise", "90"),
            Pair("Sunrise Beyond", "361"),
            Pair("Sunrise Music", "562"),
            Pair("SUPA LOVE", "544"),
            Pair("SynergySP", "367"),
            Pair("Takara Tomy A.R.T.S", "434"),
            Pair("Takeshobo", "613"),
            Pair("tamakoshi", "595"),
            Pair("TAP", "459"),
            Pair("Tapioca", "238"),
            Pair("Tatsunoko Production", "261"),
            Pair("TBS", "11"),
            Pair("TC Entertainment", "403"),
            Pair("Tear Studio", "581"),
            Pair("Techno Sound", "151"),
            Pair("Telecom Animation Film", "296"),
            Pair("Tencent Games", "605"),
            Pair("Tencent Japan", "686"),
            Pair("Tezuka Productions", "189"),
            Pair("The Answer Studio", "439"),
            Pair("TMS Entertainment", "78"),
            Pair("TMS Music", "355"),
            Pair("TMS-Kyokuchi", "389"),
            Pair("TNK", "242"),
            Pair("TO Books", "271"),
            Pair("Toei Agency", "457"),
            Pair("Toei Animation", "190"),
            Pair("Toei Video", "79"),
            Pair("Tohan Corporation", "649"),
            Pair("Toho", "197"),
            Pair("TOHO animation", "106"),
            Pair("Toho Music", "371"),
            Pair("Tohokushinsha Film Corporation", "104"),
            Pair("Tokuma Shoten", "478"),
            Pair("Tokyo Animator Gakuin", "272"),
            Pair("Tokyo Kids", "327"),
            Pair("Tokyo Movie Shinsha", "250"),
            Pair("Tokyo MX", "68"),
            Pair("Tokyopop", "464"),
            Pair("Top-Insight International", "74"),
            Pair("Toranoana", "49"),
            Pair("Toshiba EMI", "568"),
            Pair("Toshiba Entertainment", "194"),
            Pair("Toy's Factory", "360"),
            Pair("Toyo Recording", "473"),
            Pair("Triangle Staff", "392"),
            Pair("Trigger", "125"),
            Pair("Trilogy Future Studio", "530"),
            Pair("Trinity Sound", "580"),
            Pair("TROYCA", "391"),
            Pair("Tsuburaya Productions", "495"),
            Pair("Tsukuru no Mori", "636"),
            Pair("TV Aichi", "159"),
            Pair("TV Asahi", "9"),
            Pair("TV Osaka", "479"),
            Pair("TV Tokyo", "126"),
            Pair("TV Tokyo Communications", "651"),
            Pair("TV Tokyo Music", "18"),
            Pair("Twin Engine", "378"),
            Pair("TYO Animations", "264"),
            Pair("Typhoon Graphics", "688"),
            Pair("U-NEXT", "38"),
            Pair("Ufotable", "289"),
            Pair("Ultra Super Pictures", "103"),
            Pair("USEN", "284"),
            Pair("VAP", "28"),
            Pair("Vega Entertainment", "368"),
            Pair("Victor Entertainment", "350"),
            Pair("Visual Arts", "401"),
            Pair("VIZ Media", "175"),
            Pair("W-Toon Studio", "345"),
            Pair("WAO World", "254"),
            Pair("Wargaming Japan", "154"),
            Pair("Warner Bros. Japan", "61"),
            Pair("Warner Music Japan", "573"),
            Pair("Wave Master", "522"),
            Pair("Wawayu Animation", "619"),
            Pair("White Fox", "191"),
            Pair("Wicky.Records", "497"),
            Pair("Wit Studio", "120"),
            Pair("Wolfsbane", "440"),
            Pair("WOWMAX", "552"),
            Pair("WOWOW", "274"),
            Pair("Xebec", "252"),
            Pair("Y&N Brothers", "543"),
            Pair("Yahoo! Japan", "500"),
            Pair("Yokohama Animation Lab", "425"),
            Pair("Yomiko Advertising", "320"),
            Pair("Yomiuri Advertising", "17"),
            Pair("Yomiuri Shimbun", "599"),
            Pair("Yomiuri Telecasting", "165"),
            Pair("Yomiuri TV Enterprise", "82"),
            Pair("Yostar Pictures", "634"),
            Pair("Youmex", "317"),
            Pair("YTV", "294"),
            Pair("Yuewen Animation & Comics", "647"),
            Pair("Yumeta Company", "445"),
            Pair("Zero-G", "203"),
            Pair("Zexcs", "200"),
        )
    }
}
