package eu.kanade.tachiyomi.extension.id.doujinyosh

import eu.kanade.tachiyomi.multisrc.madara.Madara

class DoujinYosh : Madara("DoujinYosh", "https://doujinyosh.work", "id") {
    // source issue, doing this limits results to one page but not doing it returns no results at all
    override fun searchPage(page: Int) = ""
    override fun getGenreList() = listOf(
        Genre("4 Koma", "4koma"),
        Genre("Adult", "adult"),
        Genre("Ahegao", "ahegao"),
        Genre("Anal", "anal"),
        Genre("Animal", "animal"),
        Genre("Artist CG", "artist-cg"),
        Genre("Big Breast", "big-breast"),
        Genre("Big Penis", "big-penis"),
        Genre("Bikini", "bikini"),
        Genre("Black Mail", "black-mail"),
        Genre("Blowjob", "blowjob"),
        Genre("Body Swap", "body-swap"),
        Genre("Bondage", "bondage"),
        Genre("Cheating", "cheating"),
        Genre("Crossdressing", "crossdressing"),
        Genre("DILF", "dilf"),
        Genre("Dark Skin", "dark-skin"),
        Genre("Defloration", "defloration"),
        Genre("Demon Girl", "demon-girl"),
        Genre("Doujin", "doujin"),
        Genre("Drugs", "drugs"),
        Genre("Drunk", "drunk"),
        Genre("Elf", "elf"),
        Genre("Famele Only", "famele-only"),
        Genre("Femdom", "femdom"),
        Genre("Filming", "filming"),
        Genre("Footjob", "footjob"),
        Genre("Full Color", "full-color"),
        Genre("Furry", "furry"),
        Genre("Futanari", "futanari"),
        Genre("Glasses", "glasses"),
        Genre("Gore", "gore"),
        Genre("Group", "group"),
        Genre("Gyaru", "gyaru"),
        Genre("Harem", "harem"),
        Genre("Humiliation", "humiliation"),
        Genre("Impregnation", "impregnation"),
        Genre("Incest", "incest"),
        Genre("Inverted Nipples", "inverted-nipples"),
        Genre("Kemomimi", "kemomimi"),
        Genre("Lactation", "lactation"),
        Genre("Loli", "loli"),
        Genre("Lolipai", "lolipai"),
        Genre("MILF", "milf"),
        Genre("Maid", "maid"),
        Genre("Male Only", "male-only"),
        Genre("Miko", "miko"),
        Genre("Mind Break", "mind-break"),
        Genre("Mind Control", "mind-control"),
        Genre("Monster", "monster"),
        Genre("Monster Girl", "monster-girl"),
        Genre("Multi-Work Series", "multi-work-series"),
        Genre("Nakadashi", "nakadashi"),
        Genre("Netorare", "netorare"),
        Genre("Otona (R18)", "otona"),
        Genre("Oyakodon", "oyakodon"),
        Genre("Paizuri", "paizuri"),
        Genre("Pantyhose", "pantyhose"),
        Genre("Pregnant", "pregnant"),
        Genre("Prostitution", "prostitution"),
        Genre("Rape", "rape"),
        Genre("School Uniform", "school-uniform"),
        Genre("Sex Toy", "sex-toy"),
        Genre("Shota", "shota"),
        Genre("Sister", "sister"),
        Genre("Sleep", "sleep"),
        Genre("Slime", "slime"),
        Genre("Small Breast", "small-breast"),
        Genre("Sole Female", "sole-female"),
        Genre("Sole Male", "sole-male"),
        Genre("Stocking", "stocking"),
        Genre("Story Arc", "story-arc"),
        Genre("Sweating", "sweating"),
        Genre("Swimsuit", "swimsuit"),
        Genre("Teacher", "teacher"),
        Genre("Tentacles", "tentacles"),
        Genre("Tomboy", "tomboy"),
        Genre("Tomgirl", "tomgirl"),
        Genre("Torture", "torture"),
        Genre("Twins", "twins"),
        Genre("Virginity", "virginity"),
        Genre("Webtoon", "webtoon"),
        Genre("XRay", "xray"),
        Genre("Yandere", "yandere"),
        Genre("Yaoi", "yaoi"),
        Genre("Yuri", "yuri")
    )
}
